@startuml

class WeatherData {
  - day
  - maxTemp
  - minTemp
}

class WeatherSpreadCalculator<WeatherData, Integer>
interface Function<T, R>

WeatherSpreadCalculator ..> Function
WeatherSpreadCalculator -- WeatherData

@enduml